package rekisteriTietokanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteriTietokanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.14 09:25:39 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class AihealueTest {



  // Generated by ComTest BEGIN
  /** testGetID47 */
  @Test
  public void testGetID47() {    // Aihealue: 47
    Aihealue kouluhommat = new Aihealue(), kouluhommat2 = new Aihealue(); 
    kouluhommat.rekisteroi(); 
    kouluhommat2.rekisteroi(); 
    kouluhommat.asetaKategoria(); 
    assertEquals("From: Aihealue line: 52", 3, kouluhommat.getID()); 
    assertEquals("From: Aihealue line: 53", 4, kouluhommat2.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKategoria65 */
  @Test
  public void testGetKategoria65() {    // Aihealue: 65
    Aihealue kouluhommat = new Aihealue(); 
    kouluhommat.asetaKategoria(); 
    assertEquals("From: Aihealue line: 68", "Kouluhommat", kouluhommat.getKategoria()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi80 */
  @Test
  public void testRekisteroi80() {    // Aihealue: 80
    Aihealue kouluhommat = new Aihealue(); 
    kouluhommat.rekisteroi(); 
    assertEquals("From: Aihealue line: 83", 2, kouluhommat.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi98 */
  @Test
  public void testRekisteroi98() {    // Aihealue: 98
    Aihealue kouluhommat = new Aihealue(); 
    kouluhommat.rekisteroi(2); 
    assertEquals("From: Aihealue line: 101", 2, kouluhommat.getID()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAsetaKategoria114 */
  @Test
  public void testAsetaKategoria114() {    // Aihealue: 114
    Aihealue kouluhommat = new Aihealue(); 
    kouluhommat.rekisteroi(); 
    kouluhommat.asetaKategoria(); 
    assertEquals("From: Aihealue line: 118", "Kouluhommat", kouluhommat.getKategoria()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAsetaKategoria130 */
  @Test
  public void testAsetaKategoria130() {    // Aihealue: 130
    Aihealue kouluhommat = new Aihealue(); 
    kouluhommat.rekisteroi(); 
    kouluhommat.asetaKategoria(); 
    assertEquals("From: Aihealue line: 134", "Kouluhommat", kouluhommat.getKategoria()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString167 */
  @Test
  public void testToString167() {    // Aihealue: 167
    Aihealue aihealue = new Aihealue(); 
    aihealue.parse("   1 |  Kouluhommat"); 
    assertEquals("From: Aihealue line: 170", false, aihealue.toString().startsWith("1|Kouluhommat")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse185 */
  @Test
  public void testParse185() {    // Aihealue: 185
    Aihealue aihealue = new Aihealue(); 
    aihealue.parse("   1 |   Kouluhommat"); 
    assertEquals("From: Aihealue line: 188", 1, aihealue.getID()); 
    assertEquals("From: Aihealue line: 189", false, aihealue.toString().startsWith("1|Kouluhommat")); 
  } // Generated by ComTest END
}